### ISSUE TITLE
[BUG] Missing Contact Icons in Home Page

### ISSUE THREAD

**Issue by itsEobard2025** [skpandey885/HealhUb#123]
It appears that your Home Page is missing font-awesome icons at the Contact-Info Section. I would like to work on that Issue.
<br/>
**Contact-Info in the HomePage**
![Contact-Info @HomePage](https://user-images.githubusercontent.com/88548999/193308310-d2c27080-92fc-4778-b4b8-c0c2120ae71e.png)
<br/>
**Contact-Info in the AboutPage** _(can be found in other pages as well)_
![Contact-Info @AboutPage](https://user-images.githubusercontent.com/88548999/193308360-e908d439-6093-40a5-9659-018c52e29187.png)

Thanks for the consideration

**Comment by skpandey885** [comment]
Hey @itsEobard2025! Good to see your enthusiasm to work on the project.
Yes, It understood the issue you raised, you can proceed ahead and work on it. 
Click <a href="https://github.com/skpandey885/HealhUb/blob/main/Documentation/Getting%20started.pdf">here</a>, and follow the exact steps in order to contribute, otherwise i won't allow myself to accept the pull request. 

Happy Hacktoberfest!
