### ISSUE TITLE
Age and Gender section missing 

### ISSUE THREAD

**Issue by YatharthaRana** [skpandey885/HealhUb#125]
I want to add the age and gender section on the BMI calculator page
Also, fewer statements display as a result.
Initially
<img width="1317" alt="Screenshot 2022-10-01 at 12 53 44" src="https://user-images.githubusercontent.com/95047694/193398143-facdb1c9-ff29-4d56-b506-9566f87096cf.png">

After my modification
<img width="1403" alt="Screenshot 2022-10-01 at 12 51 00" src="https://user-images.githubusercontent.com/95047694/193398191-1e28af39-ccf2-4782-babf-f26a9f87902e.png">

Please assign me this issue

**Comment by skpandey885** [comment]
Hey @YatharthaRana! For BMI Calculation, Age and Gender is not required but still i think it will improve the content point of view. So, you can go ahead and work on this issue. Click [here](https://github.com/skpandey885/HealhUb/blob/main/Documentation/Getting%20started.pdf), and follow the exact steps in order to contribute, otherwise i won't allow myself to accept the pull request.

Happy Hacktoberfest!
