### ISSUE TITLE
Contributing.md file needed

### ISSUE THREAD

**Issue by bloodmonk7** [skpandey885/HealhUb#126]
I think one contributing.md is a must need over here. So if you provide me with all the requirements you will need or if we go with general requirements for the file, both ways I am willing to make it.
Please assign it to me if you need one Contributing.md

**Comment by skpandey885** [comment]
Hey @bloodmonk7! Can you please elaborate about the content you will add in Contributing.MD

**Comment by bloodmonk7** [comment]
We can add the general code of conduct and procedure on how to get issues assigned and it will help people who will come. This will help them and save time for understanding the procedure, If we write it for them.

**Comment by skpandey885** [comment]
I am still not clear with your thoughts, but okay! Let's give it a try! Go ahead and start working on it. I will review your PR and if it convinces me, i will merge it. Click [here](https://github.com/skpandey885/HealhUb/blob/main/Documentation/Getting%20started.pdf), and follow the exact steps in order to contribute, otherwise i won't allow myself to accept the pull request.

**Comment by bloodmonk7** [comment]
Thank You soo much for allowing me to do it, I won't dissapoint you for sure.

**Comment by skpandey885** [comment]
Hey @bloodmonk7! Can you please tell me whether your PR has been counted in the hacktoberfest or not? You can visit hacktoberfest.com to check it. Kindly let me know!
