### ISSUE TITLE
Enahacing Frontend

### ISSUE THREAD

**Issue by sumitkr2000** [skpandey885/HealhUb#134]
Hey @skpandey885 I want to add hover effect on some of the element and enhance the frontend of this amazing website. Can you please assign me this issue? Thank you !

**Comment by skpandey885** [comment]
Hey @sumitkr2000! Can you please elaborate on what kind of enhancement you want to add? Please explain!

**Comment by sumitkr2000** [comment]
@skpandey885 I want to add fontawesome icons on navbar, imporve the buttons and some fonts animations on hover etc. Please assign me this issue!

**Comment by skpandey885** [comment]
Hey @sumitkr2000 ! Good to see your enthusiasm to work on the project.
Yes, It understood the issue you raised, you can proceed ahead and work on it.
Click [here](https://github.com/skpandey885/HealhUb/blob/main/Documentation/Getting%20started.pdf), and follow the exact steps in order to contribute, otherwise i won't allow myself to accept the pull request.

Happy Hacktoberfest!

**Comment by sumitkr2000** [comment]
@skpandey885 thank you for the approval ! I will follow all the guidelines for sure.

**Comment by sumitkr2000** [comment]
Hey @skpandey885 I had a doubt! 
If I want to add font awesome icons to navbar...do I have to add it in all the pages??
