### ISSUE TITLE
Dark theme missing

### ISSUE THREAD

**Issue by YatharthaRana** [skpandey885/HealhUb#143]
I can add the dark mode to the website

**Comment by skpandey885** [comment]
Hey @YatharthaRana! Good to see your enthusiasm to work on the project.
Yes, It understood the issue you raised, you can proceed ahead and work on it.
Click [here](https://github.com/skpandey885/HealhUb/blob/main/Documentation/Getting%20started.pdf), and follow the exact steps in order to contribute, otherwise i won't allow myself to accept the pull request.
Happy Hacktoberfest!

**Comment by c99SRS** [comment]
Hi @skpandey885 can you assign this to me? I can add this.

**Comment by YatharthaRana** [comment]
@c99SRS
I have almost completed it...

**Comment by skpandey885** [comment]
> Hi @skpandey885 can you assign this to me? I can add this.

Please look for other issues!
