### ISSUE TITLE
Changing the credit theme for more neatness

### ISSUE THREAD

**Issue by Harsh-Kapoorr** [skpandey885/HealhUb#146]
I will add a more purposed credit title at the end of README and it will really look nice.
Please assign this to me.

**Comment by skpandey885** [comment]
Hey @Harsh-Kapoorr ! Good to see your enthusiasm to work on the project.
Yes, It understood the issue you raised, you can proceed ahead and work on it.
Click [here](https://github.com/skpandey885/HealhUb/blob/main/Documentation/Getting%20started.pdf), and follow the exact steps in order to contribute, otherwise i won't allow myself to accept the pull request.
Happy Hacktoberfest!
