### ISSUE TITLE
Add fonts in the website

### ISSUE THREAD

**Issue by rsinghcodes** [skpandey885/HealhUb#163]
I want to add fonts in website. Currently, the website is using the default web browser font, however we can use a custom font.

So, please assign it to me, I'll add one of the google fonts that will look good.

**Comment by skpandey885** [comment]
Hey @rsinghcodes ! Good to see your enthusiasm to work on the project.
Yes, It understood the issue you raised, you can proceed ahead and work on it.
Click [here](https://github.com/skpandey885/HealhUb/blob/main/Documentation/Getting%20started.pdf), and follow the exact steps in order to contribute, otherwise i won't allow myself to accept the pull request.
Happy Hacktoberfest!
